- name: localhost templates directory creation 
  hosts: localhost
  become: yes
  vars_files: 
    - variables.yml
  tasks:
    - name: Create mount directory
      file:
        path: "{{ path }}"
        state: directory
        owner: ansible
        group: wheel
        mode: 0775

- name: Remote machines templates directory creation
  hosts: My
  become: yes
  vars_files:
    - variables.yml
  tasks:
    - name: Create mount directory
      file:
        path: "{{ path }}"
        state: directory
        owner: ansible
        group: ansible
        mode: 0775

- name: Docker containers setup
  hosts: My1
  become: yes
  vars_files:
    - variables.yml
  tasks:
    - name: Copy config file
      template:
        src: prometheus.conf.j2
        dest: "{{ path }}/prometheus.yml"

    - name: Copy web config file
      template:
        src: /home/ansible/Monitoring/exporter_tls/web_prom.yml
        dest: "{{ path }}/web_prom.yml"

#    - name: config file
#      copy:
#        directory_mode: true
#        src: /home/ansible/Monitoring/exporter_tls/datasources/
#        dest: /home/ansible/prometheus/

#    - name: config file
#      template:
#        src: /home/ansible/Monitoring/exporter_tls/alertmanager.yml
#        dest: /home/ansible/prometheus/

#    - name: config file
#      copy:
#        src: /home/ansible/Monitoring/exporter_tls/rules
#        dest: /home/ansible/prometheus/

    - name: Run prometheus updated docker image
      docker_container:
        pull: yes
        name: Prometheus
        image: prom/prometheus:latest
        #published_ports: 9090:9090
        network_mode: host
        state: started
        volumes: 
          - /home/ansible/prometheus/:/etc/prometheus/
          - prometheus-data:/prometheus
        command:  
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--web.config.file=/etc/prometheus/web_prom.yml'
        restart: yes
        
#    - name: Run prometheus alert-manager docker image
#      docker_container:
#        pull: yes
#        name: Prometheus
#        image: prom/alertmanager:latest
#        published_ports: 9093:9093
#        #network_mode: host
#        state: started
#        volumes:
#          - /home/ansible/prometheus/:/etc/alertmanager/
#          - "./alertmanager:/config"
#          - alertmanager-data:/data
#        command:
#          - '--web.config.file=/etc/prometheus/web_prom.yml'
#          - '--config.file=/etc/alertmanager/alertmanager.yml'


    - name: Run grafana updated docker image
      docker_container:
        pull: yes
        name: Grafana
        image: grafana/grafana-oss:latest
        published_ports: 3000:3000
        state: started
        volumes: 
          - grafana-data:/var/lib/grafana
        #  - /home/ansible/prometheus/datasources/:/etc/grafana/provisioning/datasources/
        restart: yes

- name: Start node_exporter on managed nodes
  hosts: My
  become: yes
  vars_files:
    - variables.yml
  tasks:

    - name: Run node exporter updated docker image
      docker_container:
        pull: yes
        name: Exporter
        image: prom/node-exporter
        published_ports: 9100:9100
        state: started
        restart: yes
        volumes:
          - /home/ansible/prometheus/:/etc/node_exporter
        command: "--web.config.file=/etc/node_exporter/web.yml"
