- name: Node exporter for prometheus installation
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Run node exporter updated docker image
      docker_container:
        pull: yes
        name: Exporter
        image: prom/node-exporter
        published_ports: 9100:9100
        state: started
        restart: yes
        volumes:
          - /home/ansible/prometheus/:/etc/node_exporter
        command: "--web.config.file=/etc/node_exporter/web.yml"

