- name: Statistics CPU Memory Disk Utilization
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Set ufw rules
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items:
        - "9090"
        - "9100"
        - "3000"
    - name:
      service:
        name: ufw
        state: restarted

