- name: Statistics CPU Memory Disk Utilization
  hosts: Sui
  become: yes
  tasks:
    - name: Set ufw rules
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items:
        - "9090"
        - "9100"
        - "3000"
