- name: Open ports on controller for Prometheus and Grafana
  hosts: My1
  become: yes
  tasks:
    - name: Set ufw rules
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items:
        - "9090"
        - "3000"


- name: Open port on managed nodes for Node exporter
  hosts: My
  become: yes
  tasks:
    - name: Set ufw rules
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items:
        - "9100"
